/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import ca.mcgill.ecse.flexibook.model.FlexiBook;
import ca.mcgill.ecse.flexibook.model.User;

public class FlexiBookApplication {
  private static FlexiBook flexibook;  
  private static String message;
  public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new FlexiBookApplication().getGreeting());
    }

    public static FlexiBook getflexibook() {
      if (flexibook == null) {
          flexibook = new FlexiBook();
      }
      return flexibook;
  }
    public static void setflexibook(FlexiBook fb) {
      flexibook = fb;
  }
public static void setmessage(String a) {
  message=a;
  
}
public static String returnmessage() {
  return message;
 
}
}
