/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.mcgill.ecse.flexibook.application;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class FlexiBookApplicationTest {

}
